poses:
  - A:
      x: 0.35
      y: 0.24
      z: 0.4
      qx: 1
      qy: 0.0
      qz: 0.0
      qw: 0.0
  - B: 
      x: 0.53
      y: 0.24
      z: 0.4
      qx: 1.0
      qy: 0.0
      qz: 0.0
      qw: 0.0
  - C: 
      x: 0.66
      y: 0.04
      z: 0.4
      qx: 1.0
      qy: 0.0
      qz: 0.0
      qw: 0.0
  - D:
      x: 0.53
      y: -0.18
      z: 0.4
      qx: 1.0
      qy: 0.0
      qz: 0.0
      qw: 0.0
  - E: 
      x: 0.23
      y: -0.17
      z: 0.4
      qx: 1.0
      qy: 0.0
      qz: 0.0
      qw: 0.0


