poses:
  - p1:
      x: 0.4
      y: 0.0
      z: 0.6
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p2:
      x: 0.4
      y: 0.0
      z: 0.7
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p3:
      x: 0.4
      y: -0.1
      z: 0.6
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p4: 
      x: 0.4
      y: -0.1
      z: 0.7
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p5: 
      x: 0.4
      y: -0.05
      z: 0.8
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331

