poses:
  - p1:
      x: 0.4
      y: 0.0
      z: 0.6
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p2:
      x: 0.4
      y: 0.0
      z: 0.7
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p3:
      x: 0.4
      y: -0.1
      z: 0.6
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p4: 
      x: 0.4
      y: -0.1
      z: 0.7
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331
  - p5: 
      x: 0.4
      y: -0.05
      z: 1.0
      qx: -0.692
      qy: 0.203
      qz: -0.6078
      qw: 0.331

      #self.p1.orientation.x = -0.692; self.p1.orientation.y = 0.203; self.p1.orientation.z = -0.6078; self.p1.orientation.w = 0.331

