poses:
  - A:
      x: 0.25
      y: 0.2
      z: 0.85
      qx: 0.5
      qy: -0.5
      qz: 0.5
      qw: 0.5
  - B: 
      x: 0.25
      y: 0.2
      z: 0.95
      qx: 0.5
      qy: -0.5
      qz: 0.5
      qw: 0.5
  - C: 
      x: 0.0
      y: 0.2
      z: 1.05
      qx: 0.5
      qy: -0.5
      qz: 0.5
      qw: 0.5
  - D:
      x: -0.25
      y: 0.2
      z: 0.95
      qx: 0.5
      qy: -0.5
      qz: 0.5
      qw: 0.5
  - E: 
      x: -0.25
      y: 0.2
      z: 0.85
      qx: 0.5
      qy: -0.5
      qz: 0.5
      qw: 0.5