poses:
  - A:
      x: 0.4
      y: -0.05
      z: 0.5
      qx: 0.686
      qy: 0.024
      qz: 0.726
      qw: 0.000
  - B: 
      x: 0.4
      y: -0.05
      z: 1.0
      qx: 0.686
      qy: 0.024
      qz: 0.726
      qw: 0.000
  - C: 
      x: 0.4
      y: 0.05
      z: 0.5
      qx: 0.686
      qy: 0.024
      qz: 0.726
      qw: 0.000
